//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCIDRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bird_Survey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bird_Survey()
        {
            this.SurveyDetails = new HashSet<Bird_SurveyDetail>();
        }
    
        public int SurveyID { get; set; }
        public System.DateTime SurveyDate { get; set; }
        public byte SourceID { get; set; }
        public short SamplePointAreaID { get; set; }
        public byte ClimateID { get; set; }
        public byte SurveyorID { get; set; }
    
        public virtual Weather_Climate Climate { get; set; }
        public virtual Lims_SamplePointArea SamplePointArea { get; set; }
        public virtual Bird_Surveyor Surveyor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bird_SurveyDetail> SurveyDetails { get; set; }
    }
}
