//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCIDRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fish_Species> Fish_Species { get; set; }
        public virtual DbSet<Fish_SpeciesGroup> Fish_SpeciesGroup { get; set; }
        public virtual DbSet<Fish_Survey> Fish_Survey { get; set; }
        public virtual DbSet<Fish_SurveyDetail> Fish_SurveyDetail { get; set; }
        public virtual DbSet<Fish_SurveyLocation> Fish_SurveyLocation { get; set; }
    }
}
