//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCIDRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lake_ProfileDetail
    {
        public int ProfileID { get; set; }
        public decimal DepthFeet { get; set; }
        public byte ParameterID { get; set; }
        public decimal ParameterValue { get; set; }
        public string ProfileDetailNotes { get; set; }
    
        public virtual Lake_Parameter Parameter { get; set; }
        public virtual Lake_Profile Profile { get; set; }
    }
}
