//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCIDRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lake_Parameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lake_Parameter()
        {
            this.ProfileDetails = new HashSet<Lake_ProfileDetail>();
        }
    
        public byte ParameterID { get; set; }
        public string ParameterName { get; set; }
        public string ParameterFullName { get; set; }
        public string ParameterTestMethod { get; set; }
        public string ParameterUnit { get; set; }
        public bool ParameterActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lake_ProfileDetail> ProfileDetails { get; set; }
    }
}
