//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCIDRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lims_SamplePoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lims_SamplePoint()
        {
            this.Profiles = new HashSet<Lake_Profile>();
        }
    
        public byte SourceID { get; set; }
        public int SamplePointID { get; set; }
        public int ClientLocationID { get; set; }
        public string SamplePointRefID { get; set; }
        public short SamplePointAreaID { get; set; }
        public string SamplePointName { get; set; }
        public Nullable<decimal> SamplePointLatitude { get; set; }
        public Nullable<decimal> SamplePointLongitude { get; set; }
        public Nullable<short> RoleID { get; set; }
        public Nullable<bool> SamplePointAllProcess { get; set; }
        public Nullable<bool> SamplePointPermitted { get; set; }
        public Nullable<bool> SamplePointProcess { get; set; }
        public Nullable<short> SampleTypeID { get; set; }
        public string SamplePointClientSampleName { get; set; }
        public Nullable<short> POTWID { get; set; }
        public Nullable<bool> SamplePointFlowMeters { get; set; }
        public Nullable<bool> SamplePointHazzardWasteDischarge { get; set; }
        public Nullable<bool> SamplePointChemicalFeed { get; set; }
        public Nullable<bool> SamplePointSampleEquipment { get; set; }
        public string SamplePointProcessDiagnosticURL { get; set; }
        public Nullable<bool> SamplePointSurchargeable { get; set; }
        public Nullable<double> SamplePointPercentTotalOfFlow { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<int> EditedUserID { get; set; }
        public bool SamplePointActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lake_Profile> Profiles { get; set; }
        public virtual Lims_SamplePointArea SamplePointArea { get; set; }
    }
}
