//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCIDRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phyto_Species
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phyto_Species()
        {
            this.SurveyDetail2 = new HashSet<Phyto_SurveyDetail>();
        }
    
        public short SpeciesID { get; set; }
        public byte DivisionID { get; set; }
        public string SpeciesName { get; set; }
        public bool SpeciesActive { get; set; }
    
        public virtual Phyto_Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phyto_SurveyDetail> SurveyDetail2 { get; set; }
    }
}
