//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCIDRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phyto_SurveyDetail
    {
        public int SurveyID { get; set; }
        public short SpeciesID { get; set; }
        public decimal SurveyCount { get; set; }
        public bool SurveyDetailActive { get; set; }
    
        public virtual Phyto_Species Species2 { get; set; }
        public virtual Phyto_Survey Survey2 { get; set; }
    }
}
